### ISSUE TITLE
Prismic is not defined?

### ISSUE THREAD

**Issue by nickycdk** [jamespegg/prismic-nuxt#10]
When adding this package, and adding the "prismic-nuxt" to modules in the nuxt-config, and then running the application using npm run dev, im getting the error: 

Could not compile template C:\Websites\testPrismic\node_modules\prismic-nuxt\src\plugin.js: Prismic is not defined

**Comment by jamespegg** [comment]
@nickycdk Can you provide some more details about how you're using / installing `prismic-nuxt`? On a fresh install of `nuxt` and `prismic-nuxt` on v.0.2.0 I'm not getting any issues.

**Comment by jamespegg** [comment]
Closing the issue for now because there's not enough information for me to investigate the potential problem. Happy to reopen if it re-occurs

**Comment by alijaya** [comment]
Hi... I'm getting this issue also :-?...
I'm not sure what I have done wrong... I just install prismic-nuxt, and add the configuration file (nuxt.config.js):
```
modules: [
    ['prismic-nuxt', {
      endpoint: 'https://alijaya.cdn.prismic.io/api/v2',
      linkResolver: require('./prismic/link-resolver.js'),
      htmlSerializer: require('./prismic/html-serializer.js')
    }]
  ],
```

and I have this error:
```
Error: Could not compile template /home/alijayameilio/Documents/program/alijaya-website/src/node_modules/prismi  c-nuxt/src/plugin.js: Prismic is not defined
- builder.js:471 
    [src]/[nuxt]/lib/builder/builder.js:471:17
  
  - async Promise.all
  
  - builder.js:441 async Builder.generateRoutesAndFiles
    [src]/[nuxt]/lib/builder/builder.js:441:5
  
  - builder.js:165 async Builder.build
    [src]/[nuxt]/lib/builder/builder.js:165:5
```

**Comment by alijaya** [comment]
ah my bad... updating to the latest nuxt version seems to fix it :D
