### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by jamespegg** [jamespegg/prismic-nuxt#11]
Now that the library is starting to grow a bit, it needs more in-depth documentation. A couple things to consider;

- Extend #2 with more examples in the documentation itself
- Potentially generate documentation with GitHub Pages / Jekyll
- Include links to official Prismic documentation
- Include some best practices with using Prismic with Nuxt
- Include some more information about where the project is headed (e.g. roadmap)

**Comment by max8hine** [comment]
how to do such a thing like this?
```javascript

api.query(
	Prismic.Predicates.at('document.type', 'posts')
)
```
I converted above code to
```javascript
this.$prismic.api.query(
	this.$prismic.predicates.at('document.type', 'posts')
)
```
but get wrong data.

**Comment by jamespegg** [comment]
Initial set of documentation complete. Should be available on `prismic-nuxt.js.org` in a couple of days.
