### ISSUE TITLE
Preview on static site not working

### ISSUE THREAD

**Issue by cbaxter713** [jamespegg/prismic-nuxt#15]
Hi @jamespegg , I am using `prismic-nuxt` in my Nuxt project and its working beautifully.  However, I am now statically generating my site and the preview functionality doesn't work on the static site.

Reading through the Prismic docs I have found a way to create a `/preview` route in my app for when that route gets hit on the static version of the site, and it is partially handling the preview functionality.  I say partially because the initial preview load works, but then subsequent refreshes of the app don't show preview content though the front end still shows it as being in "preview mode".  

It appears that this is because the `api` that you return on the $prismic instance is not instantiated with `Prismic.getApi` but rather like:

```
let api = await Prismic.api(moduleOptions.endpoint, options);
```

Is there a reason that `Prismic.getApi` isn't being used to setup the available api there?  If it were, I believe the preview functionality could work on static sites with the slight workaround I added

**Comment by jamespegg** [comment]
I've had a look into this and it looks like `Prismic.api` is just calling `Prismic.getApi` anyway, so I don't think changing that will solve your issue specifically.

There seems to be a few different things going on here for me. Firstly, I'm not sure that pages are being properly generated for me, which is probably a bit of a red herring. Secondly, the preview does seem to work as long as a navigate away from the page I'm previewing and then go back again. This seems to be forcing the page to re-render fully.

After doing a bit of digging, it looks like statically generated pages won't run the `asyncData` function again, which essentially has the effect of caching the originally generated page (see this issue for Nuxt: https://github.com/nuxt/nuxt.js/issues/739). The recommendation there is to use the `created` hook to fetch the data again.

Are your static pages definitely generating properly? That might be a bug in it's right that'll need fixing.

**Comment by jamespegg** [comment]
Managed to figure out why pages weren't pre-rendering properly for me and confirmed the caching type behaviour. I've updated the Readme with instructions to use the `created` hook to fetch fresh content, this makes the preview functionality work consistently for me.
