### ISSUE TITLE
Load Prismic CDN as non blocking resource

### ISSUE THREAD

**Issue by JoepSnijders** [jamespegg/prismic-nuxt#16]
Hi! A Lighthouse audit on my statically generated site returns that prismic.min.js should be loaded as non-blocking. Perhaps we can add the defer property to the script tag when the site gets generated?

<img width="659" alt="defer" src="https://user-images.githubusercontent.com/5106635/52975073-41ad6500-33c4-11e9-9ed3-48297bc00c01.png">

**Comment by jamespegg** [comment]
Thanks for the suggestion @JoepSnijders , this is now available in v0.4.0. It's turned off by default just in case it breaks existing projects. All you have to do is add in a `deferLoad: true` into the options in your `nuxt.config.js`.

**Comment by JoepSnijders** [comment]
@jamespegg That's awesome! Thanks for implementing this feature.
