### ISSUE TITLE
Node version 8 support

### ISSUE THREAD

**Issue by TheDiehard22** [jamespegg/prismic-nuxt#18]
Hey there. I am currently trying out this package and I'm trying to release it on Netlify. However, Netlify's highest supported node version is 8.10. 

Is node >= 9.0.0 really required? If no - could you lower the version to 8?

**Comment by jamespegg** [comment]
@TheDiehard22 No worries, you should be able to use it on Node 8 from v0.5.0 onwards. I can't guarantee that'll it work exactly as expected with the other dependencies (namely `prismic-dom` and `prismic-javascript`), but it's passing tests on Travis.

When v8 drops out of LTS maintenance at the end of the year I might have to come back to this one and reconsider, but for now it should work.

**Comment by TheDiehard22** [comment]
Thanks! I upgraded to 0.5.0 and deployed it on Netlify without any issues. Deprecating at the end of the year seems fine as they will probably support node 10 by then.
