### ISSUE TITLE
Add examples folder

### ISSUE THREAD

**Issue by jamespegg** [jamespegg/prismic-nuxt#2]

**Comment by CalebKester** [comment]
Do you have a list of examples you'd like? I'm sure there are some of us that would be willing to help start some examples.

- html-serializer and linkresolver usage
- asyncData example (see readme)
- nuxtServerInit in store\index.js
- Generate routes from prismic query (see #14 not really prismic-nuxt but it's it's something generate users will need)

**Comment by jamespegg** [comment]
Thanks @CalebKester , that'd be great. I've just finished setting up docusaurus to generate documentation. This should be available on `prismic-nuxt.js.org` in a couple of days.

Happy to take pull requests for some extra documentation (especially around nuxtServerInit and generating routes). At the moment it has a getting started guide and covers all the config options.
