### ISSUE TITLE
Update `prismic-javascript` package version

### ISSUE THREAD

**Issue by brockdusome** [jamespegg/prismic-nuxt#26]
As per [this](https://github.com/prismicio/prismic-javascript/pull/78) article, update `prismic-javascript` to at least `v2.02` to enable the proper functionality for `$prismic.predicates.at(...)`

**Comment by jamespegg** [comment]
Thanks @brockdusome. Looks like there's an issue with `v2.1.0`, but will update as soon as that's resolved

**Comment by Atinux** [comment]
Thank you so much for this module @jamespegg 👏 

What's the issue with `v2.1.0`?

**Comment by jamespegg** [comment]
My pleasure @Atinux :)

Builds seemed to be failing on `v2.1.0` (https://github.com/prismicio/prismic-javascript/issues/92) but looks to be fixed as of yesterday. I'll update to `v2.1.1` now.

**Comment by jamespegg** [comment]
Solved in `v0.5.2`
