### ISSUE TITLE
How to import linkResolver and htmlSerializer from another file?

### ISSUE THREAD

**Issue by alijaya** [jamespegg/prismic-nuxt#28]
Hi I want to ask if it's possible to separate the linkResolver file and htmlSerializer file from nuxt.config.js
If it's yes, how? Thanks :D

**Comment by jamespegg** [comment]
Hi @alijaya ,

Yep, that should be possible by just putting the functions in a separate file and ensuring you've set `module.exports`. You can then import them like any normal file or module in `nuxt.config.js`.

Cheers,
James
